#!/usr/bin/env node

/**
 * Verification Script: ADR Claims
 * 
 * Prüft ADR-Claims gegen Code:
 * - Dateien existieren (Pattern: `Erstelle \`src/path/file.ts\``)
 * - Funktionen existieren (Pattern: `functionName()`)
 * - Imports funktionieren
 */

const fs = require('fs');
const path = require('path');

const errors = [];
const warnings = [];

/**
 * Rekursive Suche nach einem Pattern in einem Verzeichnis
 */
function searchInDirectory(dir, pattern) {
  const regex = new RegExp(`\\b${pattern}\\b`);
  const files = fs.readdirSync(dir);
  
  for (const file of files) {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    
    if (stat.isDirectory()) {
      if (searchInDirectory(filePath, pattern)) {
        return true;
      }
    } else if (file.endsWith('.ts') || file.endsWith('.js')) {
      const content = fs.readFileSync(filePath, 'utf-8');
      if (regex.test(content)) {
        return true;
      }
    }
  }
  return false;
}

/**
 * Extrahiert Claims aus einem ADR
 */
function extractClaimsFromAdr(adrPath) {
  const content = fs.readFileSync(adrPath, 'utf-8');
  const claims = [];
  
  // Pattern: "Erstelle `src/path/file.ts`"
  // Pattern: "Erstelle: `src/path/file.ts`"
  // Pattern: "- `src/path/file.ts`"
  const createPattern = /(?:Erstelle|Erstellt|Erstellen|Create|Created|Creates)\s*:?\s*`([^`]+)`/gi;
  let match;
  while ((match = createPattern.exec(content)) !== null) {
    const filePath = match[1].trim();
    // Ignoriere Markdown-Links und andere nicht-Datei-Pfade
    if (filePath.match(/\.(ts|js|json|md|yml|yaml)$/)) {
      claims.push({
        type: 'file-exists',
        file: filePath,
        adr: path.basename(adrPath),
        line: content.substring(0, match.index).split('\n').length
      });
    }
  }
  
  // Pattern: "function foo()" oder "function foo("
  // Pattern: "export function foo()"
  // Pattern: "class Foo"
  // Pattern: "export class Foo"
  const funcPattern = /(?:export\s+)?(?:function|class|const|let|var)\s+(\w+)/g;
  const funcMatches = [];
  while ((match = funcPattern.exec(content)) !== null) {
    const funcName = match[1];
    // Nur wenn es in einem Code-Block oder als Claim erwähnt wird
    const context = content.substring(Math.max(0, match.index - 50), match.index + 50);
    if (context.includes('```') || context.includes('`') || context.includes('implementiert')) {
      funcMatches.push({
        name: funcName,
        adr: path.basename(adrPath),
        line: content.substring(0, match.index).split('\n').length
      });
    }
  }
  
  // Vereinfachte Funktion-Claims: Nur wenn explizit erwähnt
  const explicitFuncPattern = /(?:implementiert|implemented|erstellt|created)\s+(?:die\s+)?(?:Funktion|function|Klasse|class)\s+`?(\w+)`?/gi;
  while ((match = explicitFuncPattern.exec(content)) !== null) {
    const funcName = match[1];
    if (!funcMatches.find(f => f.name === funcName)) {
      funcMatches.push({
        name: funcName,
        adr: path.basename(adrPath),
        line: content.substring(0, match.index).split('\n').length,
        explicit: true
      });
    }
  }
  
  // Pattern für automatisch generierte ADRs: Funktionen/Klassen in Backticks unter "Hauptfunktionen" oder "Hauptklassen"
  // Pattern: "- `FunctionName()`" oder "- `ClassName`" oder "`FunctionName.`"
  const autoGenPattern = /(?:Hauptfunktionen|Hauptklassen|Functions|Classes)[\s\S]*?`([A-Za-z_][A-Za-z0-9_]*)(?:\(|\.|`)/g;
  while ((match = autoGenPattern.exec(content)) !== null) {
    const funcName = match[1];
    // Ignoriere generische Namen und Methoden-Namen (nur Klassen/Funktionen auf oberster Ebene)
    const ignoreList = ['other', 'unknown', 'getChildren', 'getTreeItem', 'refresh', 'getDocumentationFiles', 'Thenable', 'TreeItem', 'ExtensionContext'];
    if (!ignoreList.includes(funcName) && funcName.length > 2) {
      if (!funcMatches.find(f => f.name === funcName)) {
        funcMatches.push({
          name: funcName,
          adr: path.basename(adrPath),
          line: content.substring(0, match.index).split('\n').length,
          explicit: false, // Nicht explizit, aber sollte existieren
          autoGenerated: true
        });
      }
    }
  }
  
  // Zusätzliches Pattern: Funktionen/Klassen die direkt in Backticks erwähnt werden (z.B. "`activate()`")
  const backtickPattern = /`([A-Za-z_][A-Za-z0-9_]*)\(\)`/g;
  while ((match = backtickPattern.exec(content)) !== null) {
    const funcName = match[1];
    // Nur wenn es in einem relevanten Kontext ist (nicht in Code-Blöcken)
    const contextBefore = content.substring(Math.max(0, match.index - 100), match.index);
    const contextAfter = content.substring(match.index, Math.min(content.length, match.index + 100));
    // Ignoriere Code-Blöcke (```)
    if (!contextBefore.includes('```') && !contextAfter.includes('```')) {
      // Nur wenn es in einem relevanten Abschnitt ist
      if (contextBefore.includes('Hauptfunktionen') || contextBefore.includes('Functions') || 
          contextBefore.includes('activate') || contextBefore.includes('deactivate')) {
        if (!funcMatches.find(f => f.name === funcName)) {
          funcMatches.push({
            name: funcName,
            adr: path.basename(adrPath),
            line: content.substring(0, match.index).split('\n').length,
            explicit: false,
            autoGenerated: true
          });
        }
      }
    }
  }
  
  claims.push(...funcMatches.map(f => ({
    type: 'function-exists',
    name: f.name,
    adr: f.adr,
    line: f.line,
    explicit: f.explicit
  })));
  
  return claims;
}

/**
 * Lädt die Path-Alias-Map aus .database-plugin/path-aliases.json
 */
function loadAliasMap(workspaceRoot) {
  const aliasMapPath = path.join(workspaceRoot, '.database-plugin', 'path-aliases.json');
  if (fs.existsSync(aliasMapPath)) {
    try {
      const content = fs.readFileSync(aliasMapPath, 'utf-8');
      return JSON.parse(content);
    } catch (error) {
      // Ignore errors loading alias map
      return {};
    }
  }
  return {};
}

/**
 * Resolved einen Pfad mit Hilfe der Alias-Map
 */
function resolvePathWithAlias(filePath, workspaceRoot, aliasMap) {
  // Normalisiere den Pfad (forward slashes)
  const normalized = filePath.replace(/\\/g, '/');
  
  // Prüfe ob es einen Alias gibt
  if (aliasMap[normalized]) {
    return path.join(workspaceRoot, aliasMap[normalized]);
  }
  
  // Fallback: Original-Pfad
  return path.join(workspaceRoot, filePath);
}

/**
 * Findet alle src/ Verzeichnisse (und app/ für Next.js) mit Hilfe der Alias-Map
 */
function findAllSourceDirectories(workspaceRoot, aliasMap) {
  const sourceDirs = [];
  
  // Standard: src/ im Workspace-Root
  const standardSrc = path.join(workspaceRoot, 'src');
  if (fs.existsSync(standardSrc)) {
    sourceDirs.push(standardSrc);
  }
  
  // Suche in Alias-Map nach src/ Pfaden
  for (const [alias, target] of Object.entries(aliasMap)) {
    if (alias.startsWith('src/') || alias.includes('/src/')) {
      // Extrahiere das Plugin-Root aus dem Target
      const targetParts = target.split('/');
      const srcIndex = targetParts.indexOf('src');
      if (srcIndex > 0) {
        const pluginRoot = targetParts.slice(0, srcIndex).join('/');
        const srcDir = path.join(workspaceRoot, pluginRoot, 'src');
        if (fs.existsSync(srcDir) && !sourceDirs.includes(srcDir)) {
          sourceDirs.push(srcDir);
        }
      }
    }
  }
  
  // Suche rekursiv nach src/ Verzeichnissen (max. 2 Ebenen tief)
  try {
    const searchDirs = [
      workspaceRoot,
      ...fs.readdirSync(workspaceRoot, { withFileTypes: true })
        .filter(dirent => dirent.isDirectory() && !dirent.name.startsWith('.') && dirent.name !== 'node_modules')
        .map(dirent => path.join(workspaceRoot, dirent.name))
    ];
    
    for (const searchDir of searchDirs) {
      // src/ Verzeichnisse
      const srcDir = path.join(searchDir, 'src');
      if (fs.existsSync(srcDir) && !sourceDirs.includes(srcDir)) {
        sourceDirs.push(srcDir);
      }
      
      // app/ Verzeichnisse (Next.js)
      const appDir = path.join(searchDir, 'app');
      if (fs.existsSync(appDir) && !sourceDirs.includes(appDir)) {
        sourceDirs.push(appDir);
      }
    }
  } catch (error) {
    // Ignore errors
  }
  
  return sourceDirs.length > 0 ? sourceDirs : null;
}

/**
 * Verifiziert einen Claim
 */
function verifyClaim(claim, workspaceRoot) {
  // Lade Alias-Map
  const aliasMap = loadAliasMap(workspaceRoot);
  
  if (claim.type === 'file-exists') {
    // Versuche zuerst mit Alias-Map
    const resolvedPath = resolvePathWithAlias(claim.file, workspaceRoot, aliasMap);
    const exists = fs.existsSync(resolvedPath);
    
    if (!exists) {
      // Fallback: Original-Pfad
      const fullPath = path.join(workspaceRoot, claim.file);
      const existsOriginal = fs.existsSync(fullPath);
      
      if (!existsOriginal) {
        // Prüfe ob es als .js in out/ existiert (kompilierte Version)
        const jsPath = fullPath.replace(/^src\//, 'out/').replace(/\.ts$/, '.js');
        const jsExists = fs.existsSync(path.join(workspaceRoot, jsPath));
        
        if (jsExists) {
          warnings.push({
            adr: claim.adr,
            line: claim.line,
            claim: `File ${claim.file} exists as compiled ${jsPath}, but source not found`,
            type: 'file-exists'
          });
          return true; // Akzeptabel
        }
        
        errors.push({
          adr: claim.adr,
          line: claim.line,
          claim: `File ${claim.file} does not exist`,
          type: 'file-exists'
        });
        return false;
      }
    }
    return true;
  }
  
  if (claim.type === 'function-exists') {
    try {
      // Finde alle src/ und app/ Verzeichnisse mit Hilfe der Alias-Map
      const sourceDirs = findAllSourceDirectories(workspaceRoot, aliasMap);
      if (!sourceDirs || sourceDirs.length === 0) {
        warnings.push({
          adr: claim.adr,
          line: claim.line,
          claim: `Could not verify function ${claim.name} (src/ or app/ directory not found)`,
          type: 'function-exists'
        });
        return true;
      }
      
      // Rekursive Suche in allen TypeScript-Dateien (src/ und app/)
      let found = false;
      for (const srcDir of sourceDirs) {
        if (searchInDirectory(srcDir, claim.name)) {
          found = true;
          break;
        }
      }
      
      if (!found) {
        if (claim.explicit || claim.autoGenerated) {
          // Explizite Claims und auto-generierte Claims sollten existieren
          errors.push({
            adr: claim.adr,
            line: claim.line,
            claim: `Function/class ${claim.name} not found in codebase${claim.autoGenerated ? ' (auto-generated ADR)' : ''}`,
            type: 'function-exists'
          });
          return false;
        } else {
          // Nicht-explizite Claims sind nur Warnungen
          warnings.push({
            adr: claim.adr,
            line: claim.line,
            claim: `Function/class ${claim.name} mentioned but not found (may be non-critical)`,
            type: 'function-exists'
          });
          return true;
        }
      }
      return true;
    } catch (error) {
      warnings.push({
        adr: claim.adr,
        line: claim.line,
        claim: `Could not verify function ${claim.name}: ${error.message}`,
        type: 'function-exists'
      });
      return true; // Nicht kritisch wenn Verification fehlschlägt
    }
  }
  
  return true;
}

/**
 * Findet das docs/ Verzeichnis durch intelligente Suche.
 * Sucht im gegebenen Verzeichnis und in Parent-Verzeichnissen (max. 5 Ebenen).
 * 
 * @param startDir Das Verzeichnis, von dem aus gesucht werden soll
 * @param maxDepth Maximale Anzahl von Parent-Ebenen, die durchsucht werden sollen (default: 5)
 * @returns Der Pfad zum docs/ Verzeichnis oder null, wenn nicht gefunden
 */
function findDocsDirectory(startDir, maxDepth = 5) {
  let currentDir = path.resolve(startDir);
  let depth = 0;

  while (depth < maxDepth) {
    const docsPath = path.join(currentDir, 'docs');
    if (fs.existsSync(docsPath)) {
      const stats = fs.statSync(docsPath);
      if (stats.isDirectory()) {
        return docsPath;
      }
    }

    const parentDir = path.dirname(currentDir);
    
    // Stop if we've reached the root (parent equals current)
    if (parentDir === currentDir) {
      break;
    }

    currentDir = parentDir;
    depth++;
  }

  return null;
}

/**
 * Hauptfunktion
 */
function main() {
  // Workspace-Root bestimmen:
  // 1. Falls als erstes Argument übergeben, verwenden
  // 2. Sonst process.cwd() verwenden (wird vom MCP-Tool als cwd gesetzt)
  // 3. Fallback: __dirname + '/..' (für Kompatibilität mit direktem Aufruf)
  let workspaceRoot;
  
  if (process.argv.length >= 3 && process.argv[2] !== '--' && process.argv[2] !== '--verbose') {
    // Erstes Argument ist Workspace-Root (vor -- oder --verbose)
    workspaceRoot = path.resolve(process.argv[2]);
    // Argument aus process.argv entfernen, damit --verbose weiterhin funktioniert
    process.argv.splice(2, 1);
  } else {
    // Standard: process.cwd() (wird vom MCP-Tool als cwd gesetzt)
    workspaceRoot = process.cwd();
    
    // Fallback: __dirname + '/..' (nur wenn process.cwd() nicht das richtige Verzeichnis ist)
    // Prüfe, ob docs/ in process.cwd() gefunden werden kann
    const docsFromCwd = findDocsDirectory(workspaceRoot);
    if (!docsFromCwd) {
      // Fallback: Versuche __dirname + '/..'
      const fallbackRoot = path.join(__dirname, '..');
      const docsFromFallback = findDocsDirectory(fallbackRoot);
      if (docsFromFallback) {
        workspaceRoot = fallbackRoot;
      }
    }
  }

  // docs/ Verzeichnis finden (intelligente Suche)
  const docsPath = findDocsDirectory(workspaceRoot);
  if (!docsPath) {
    console.log('⚠️  ADR directory not found, skipping verification');
    console.log(`   Searched from: ${workspaceRoot}`);
    process.exit(0);
  }

  const adrDir = path.join(docsPath, 'adr');
  
  if (!fs.existsSync(adrDir)) {
    console.log('⚠️  ADR directory not found, skipping verification');
    console.log(`   Docs directory found: ${docsPath}`);
    console.log(`   ADR directory expected: ${adrDir}`);
    process.exit(0);
  }
  
  console.log('🚀 Starting ADR claims verification...\n');
  
  const adrFiles = fs.readdirSync(adrDir).filter(f => f.endsWith('.md') && f !== 'TEMPLATE.md');
  
  let totalClaims = 0;
  let verifiedClaims = 0;
  
  for (const adrFile of adrFiles) {
    const adrPath = path.join(adrDir, adrFile);
    const claims = extractClaimsFromAdr(adrPath);
    
    totalClaims += claims.length;
    
    for (const claim of claims) {
      const verified = verifyClaim(claim, workspaceRoot);
      if (verified) {
        verifiedClaims++;
      }
    }
  }
  
  console.log(`📊 Verification Summary:`);
  console.log(`   Total claims: ${totalClaims}`);
  console.log(`   Verified: ${verifiedClaims}`);
  console.log(`   Errors: ${errors.length}`);
  console.log(`   Warnings: ${warnings.length}`);
  
  if (errors.length > 0) {
    console.log('\n❌ ERRORS:');
    errors.forEach((err, index) => {
      console.log(`   ${index + 1}. ${err.adr}:${err.line}`);
      console.log(`      ${err.claim}`);
    });
  }
  
  if (warnings.length > 0 && process.argv.includes('--verbose')) {
    console.log('\n⚠️  WARNINGS:');
    warnings.forEach((warn, index) => {
      console.log(`   ${index + 1}. ${warn.adr}:${warn.line}`);
      console.log(`      ${warn.claim}`);
    });
  }
  
  if (errors.length > 0) {
    console.log('\n❌ ADR verification FAILED');
    console.log('   Run with --verbose to see warnings');
    process.exit(1);
  } else {
    console.log('\n✅ ADR verification PASSED');
    if (warnings.length > 0) {
      console.log(`   (${warnings.length} warnings, run with --verbose to see details)`);
    }
    process.exit(0);
  }
}

main();
